name: Limpar Artefatos Antigos

on:
  workflow_dispatch: # Permite execução manual

jobs:
  cleanup:
    name: Remover Artefatos Antigos
    runs-on: ubuntu-latest

    steps:
      - name: Listar Artefatos
        run: |
          echo "Listando artefatos disponíveis..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
          | jq '.artifacts[] | {id: .id, name: .name, size: .size_in_bytes, expired: .expired}'

      - name: Remover Artefatos Expirados
        run: |
          echo "Excluindo artefatos expirados..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
          | jq '.artifacts[] | select(.expired == true) | .id' \
          | xargs -I {} \
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts/{}

      - name: Listar Artefatos
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
          | jq '.artifacts[] | {id: .id, name: .name}'

      - name: Remover Artefato Específico
        run: |
          echo "Excluindo o artefato app-debug..."
          curl -X DELETE \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts/ID_DO_ARTEFATO

      - name: Remover Artefatos Antigos
        run: |
          echo "Excluindo artefatos antigos..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
          | jq '.artifacts[] | select(.created_at < "'$(date -I -d '7 days ago')'") | .id' \
          | xargs -I {} \
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts/{}